### ISSUE TITLE
Hi, any chance of sharing the model weights?

### ISSUE THREAD

**Issue by windring** [ChrisNick92/deep-audio-fingerprinting#3]
Hey there!
I've been checking out your audio fingerprinting project and it looks really interesting. I was wondering if you might be able to share the pretrained model weights (`fingerprinter.pt`)?
It would be great to play around with the model without having to train from scratch. No worries if it's not possible though.
Thanks for sharing your work either way!

**Comment by ChrisNick92** [comment]
Hello @windring !

Of course I can share, I've just uploaded the model, the faiss index (containing the fingerprints in quantized form), as well as the json correspondence with the song names in this dropbox folder: [https://www.dropbox.com/scl/fo/hcbhutsp9geypo2vtc9z6/APkK5A0HdK4lXsR-FM9TDb4?rlkey=s87ajlxhdwu13sbpnfgogfjou&st=kt9tz1lm&dl=0](https://www.dropbox.com/scl/fo/hcbhutsp9geypo2vtc9z6/APkK5A0HdK4lXsR-FM9TDb4?rlkey=s87ajlxhdwu13sbpnfgogfjou&st=kt9tz1lm&dl=0).

This model is trained on 1000 commercial songs and on the medium part of the FMA dataset ([https://github.com/mdeff/fma](https://github.com/mdeff/fma)).

Of course you extract the fingerprints of your songs of choice, but note that if you add a lot of new songs (>1000) the performance is expected to drop and you'll need to retrain.

PS Check that you can download the items in the folder, and don't hesitate to comment again if you have any questions with regard to the repo.

**Comment by windring** [comment]
Thank you so much for generously sharing the pretrained model weights and associated files! I sincerely appreciate your openness and willingness to help.

The Dropbox link you provided is incredibly useful, and I've successfully downloaded all the files. Having these resources will allow me to experiment with the model directly without having to train from scratch, which is immensely helpful for my research.

I really appreciate that you've used a diverse dataset for your project, including both commercial songs and the FMA dataset. This undoubtedly enhances the model's robustness and versatility. I'll keep in mind your advice about the potential performance impact when adding a large number of new songs.

Thank you again for your generous sharing and detailed explanations. If I encounter any issues while using the files, I'll definitely reach out with another comment.

Wishing you all the best with your work!
